const main = async () => {};

main().catch((err) => console.log(err));
